
public class Problem2 {
	
	
	/*
	 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
	   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
       By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
	 */


	public static void main(String[] args) {
	
		double num1 = 1;
		double num2 = 2;
		double num3 = 0;
		double sum = 2;
		
		double hold1 = 0;
		double hold2 = 0;
		double hold3 = 0;
		
		
		
		
		
		while(num3 < 4000000){
		
			num3 = num1 + num2;
			
			System.out.println(num1);
			System.out.println(num2);
			System.out.println(num3);
		
			if (num3%2==0){
				sum += num3;
				
			}
			
			hold2 = num2;
			hold3 = num3;
			
			num2 = hold3;
			num1 = hold2;
			

	
		
		
	}//end of while loop
		
		System.out.println(sum);
		

		
		
	}
	

	

}
